version: "3.3"

services:
  percona:
    image: percona:5.7.21
    command:
      - "mysqld"
      - "--max-connections=1000"
      - "--innodb_buffer_pool_size=2G"
      - "--innodb_log_file_size=1G"
      - "--innodb_flush_method=O_DIRECT"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_USER=internal
      - MYSQL_PASSWORD=dev
      - MYSQL_DATABASE=test
    deploy:
      mode: replicated
      replicas: 1
      labels: [DB=MYSQL]
    volumes:
      - mysqldata:/var/lib/mysql

  redis:
    image: redis:4.0.8-alpine
    command:
      - "redis-server"
      - "--appendonly yes"
      - "--requirepass dev"
      - "--maxmemory 256mb"
      - "--maxmemory-policy volatile-lru"
    ports:
      - "6379:6379"
    deploy:
      mode: replicated
      replicas: 1
      labels: [DB=REDIS]
    volumes:
      - redisdata:/data

  parity:
    image: parity/parity:v1.9.5
    command:
      - "--config=dev"
      - "--ui-port=8186"
      - "--jsonrpc-port=8645"
      - "--ws-port=8646"
      - "--unsafe-expose"
      - "--reseal-min-period=0"
      - "--gasprice=0"
      - "--base-path=/root/.local/share/io.parity.ethereum"
    ports:
      - "8186:8186"
      - "8645:8645"
      - "8646:8646"
      - "8666:8666"
      - "30303:30303"
    deploy:
      mode: replicated
      replicas: 1
      labels: [DB=PARITY]
    volumes:
      - chaindata:/root/.local/share/io.parity.ethereum

volumes:
  mysqldata:
    driver: local
  redisdata:
    driver: local
  chaindata:
    driver: local
# Usage
# docker stack deploy --compose-file=infra/local/compose.yml storage;

# To create your own DB, for example dev
# CONTAINER_NAME=$(docker container ls --format '{{.Names}}' | grep percona) && docker exec -i $CONTAINER_NAME mysql -u root -e "DROP DATABASE IF EXISTS dev;CREATE DATABASE dev;GRANT ALL PRIVILEGES ON dev.* TO 'internal'@'%';";

